### ISSUE TITLE
Labels are truncated when graph height is under 100

### ISSUE THREAD

**Issue by Nickduino** [kalkih/mini-graph-card#1151]
![image](https://github.com/user-attachments/assets/74464440-c535-4b60-a853-defd552b8347)
(There is enough space to mode them up a bit)

They're slightly truncated at 100, mind you:

![image](https://github.com/user-attachments/assets/3b19936f-bf9b-4c4a-98da-a7f5d96c7215)

Good at 120:

![image](https://github.com/user-attachments/assets/c6ef8c78-a7a7-4c51-b90d-fb4ce6fd8e51)

**Comment by ildar170975** [comment]
How is it shown with default options for font and height?
Adapting a picture for a particular size an be done by card-mod.
The mini-graph-card provides a basic set of options to style a card.

**Comment by Nickduino** [comment]
> with default options for font

![image](https://github.com/user-attachments/assets/3862aeb6-dd1b-4829-b542-48f4be91ff22)


As for the height, I showed it in the first post: the text is ok but the border is truncated.

**Comment by ildar170975** [comment]
Here is my default look:
![image](https://github.com/user-attachments/assets/a3550150-f4fc-40f2-ab60-50d42278ba34)
No clipping is here.

Height = 100:
![image](https://github.com/user-attachments/assets/f0e5c48f-99bf-4907-9db7-7130675789b8)

Height = 80:
![image](https://github.com/user-attachments/assets/32e79112-a100-4b43-85ba-bbc6de05aa80)

Height = 63: a clipping is about to happen:
![image](https://github.com/user-attachments/assets/d766bd22-fa82-456b-9377-ef93aa44456f)

**Conclusion**: depends on a particular client.
Clipping of a bottom label occurs if a graph height < height of a `.graph__labels` element (which in my case is ~58px).
If you observe a clipping - either increase a graph height or play with fonts for labels.

**Comment by Nickduino** [comment]
In your examples, all graphs seem pretty wide. Can you try with a different width?

> Clipping of a bottom label occurs if a graph height < height of a `.graph__labels` element (which in my case is ~58px)

I don't know about that, my first example was with a height of 78 and you see some clipping with my height at 100.

**Comment by ildar170975** [comment]
> my first example was with a height of 78 and you see some clipping with my height at 100.

A height of `.graph__labels` element depends on a font-size used (`calc(0.15em + 8.5px);`).

> seem pretty wide

Because this is a STANDARD width.
Placing cards into stacks/grid makes them narrow.
In case of a `mini-graph-card` it will affect a graph's height:
height 130 - causes a height ~130px:
![image](https://github.com/user-attachments/assets/5fdf6115-09ec-486f-9325-655b636a5ed3)

But when the same card is placed into a horiz stack - the height becomes more than 2 times smaller:
![image](https://github.com/user-attachments/assets/a2e6272c-defd-4b9d-b5a7-a13ccc7bddca)
because the svg is scaled down - like a stock `history-graph`:
![image](https://github.com/user-attachments/assets/d524c70f-333d-4c92-bc81-387b29f23b2e)

You should either avoid using graphs in a stack/grid, or card-mod them additionally.

**Comment by ildar170975** [comment]
I am going to close this issue since there is nothing buggy here.
When not scaled down (i.e. when not placed into a stack) the card shows labels not clipped (if a height is not smaller than needed).
All additional alterations may be done by card-mod.

The issue is closed - but the discussion may continue of course.

**Comment by Nickduino** [comment]
> I am going to close this issue since there is nothing buggy here.

But it is. You can't say it's normal to not be able to use Sections with a card.

**Comment by ildar170975** [comment]
What is really present - a behaviour in a Grid card:
![image](https://github.com/user-attachments/assets/727e4fce-cec0-4f94-aaad-b2257670d4e0)
Currently this cab be solved by smth like
```
    card_mod:
      style: |
        :host {height: 100%}
```
and this could be implemented natively...

**Comment by Nickduino** [comment]
> very little of experienced users use sections

Don't reserve the card to experienced users. How are we supposed to build experience if we can't use the cards?


> since it is still in beta

In that case, don't close the issue: put it on the back burner until section is out of beta.

**Comment by ildar170975** [comment]
> How are we supposed to build experience if we can't use the cards?

The normal "not-sections" view is fully operational.

> In that case, don't close the issue: put it on the back burner until sections is out of beta if you wish.

Not a problem, can reopen; but the issue is not related to sections actually, it is about SCALING down a card with a user tries to paste to a narrow grid cell. Note that even stock cards may look ugly when placed into Grid.

**Comment by Nickduino** [comment]
> The normal "not-sections" view is fully operational. Sections is a merely an ADDITIONAL way to build a view.

I was refering to your point about "experienced users"


> the issue is not related to sections actually, it is about SCALING down a card

Alright. It's still an issue. A **Mini**-graph-card should be able to offer a compact view. Here is your default card vs a default `graph: line`:

![image](https://github.com/user-attachments/assets/3474dd86-a8ed-4348-b196-1ba6ffefb3c3)
