### ISSUE TITLE
Aggregate max combined with group by date always shows a 0 value for the first group

### ISSUE THREAD

**Issue by KevinD-87** [kalkih/mini-graph-card#429]
I have the following configuration to show the total kWh consumption per day based on the max value of a sensor for that day. The first day always shows as value 0, even when changing the hours to show to 144 (6 days), 120 (5 days), ...
```
aggregate_func: max
entities:
  - color: orange
    entity: sensor.todays_consumption
group_by: date
hours_to_show: 168
icon: 'mdi:flash'
show:
  graph: bar
  icon: false
  labels: true
  name: false
type: 'custom:mini-graph-card'
```
Todays consumption is a calculated sensor based on the difference between an input_number, which gets set through an automation to the value of the total consumption sensor at 23:59 each day (sensor source: Shelly 3EM), and the current total consumption sensor.

7 days (hours_to_show: 168)
![image](https://user-images.githubusercontent.com/9356821/91464168-8c971b00-e88c-11ea-8b16-31a0a20506fe.png)
![image](https://user-images.githubusercontent.com/9356821/91464884-5c9c4780-e88d-11ea-970d-082d46813c76.png)

6 days (hours_to_show: 144)
![image](https://user-images.githubusercontent.com/9356821/91465236-d46a7200-e88d-11ea-844f-a5afb152fd52.png)

See for 7 days, the value for last Saturday is set to 9 kWh, whereas for 6 days it shows up as 0 kWh.

**Comment by kalkih** [comment]
I don't see an aggregate function specified in your config.
Anyway, please try `aggregate_func: last` and see if that makes any difference.

Btw, are you sure you're on the latest version of the card, looks like the issue fixed with https://github.com/kalkih/mini-graph-card/pull/327.

**Comment by KevinD-87** [comment]
> I don't see an aggregate function specified in your config.
> Anyway, please try `aggregate_func: last` and see if that makes any difference.
> 
> Btw, are you sure you're on the latest version of the card, looks like the issue fixed with #327.

Thanks for your reply. It seems I messed up the code block in my original post. I've edited my original post to include the `aggregate_func: max` I'm using.
I'm running version 0.9.4, which is the latest one.
Using `aggregate_func: last` only shows the value for the current day, all other days end up showing 0 kWh.

**Comment by b0kar** [comment]
Hey,

Same here.
Used the same code as in the readme.
`entities:
  - aggregate_func: max
    color: null
    entity: sensor.outside_temp
    name: Max
  - aggregate_func: min
    entity: sensor.outside_temp
    name: Min
  - aggregate_func: avg
    color: green
    entity: sensor.outside_temp
    name: Avg
group_by: date
hours_to_show: 96
name: Temp outside daily (last week)
type: 'custom:mini-graph-card'`
For the first element, (whatever the value of hours_to_show is), min, max and average always have the same value

<img width="383" alt="Screenshot 2020-09-16 at 13 42 43" src="https://user-images.githubusercontent.com/17979270/93338023-2d447f00-f82a-11ea-80a8-059521a0b6a6.png">

**Comment by RomRider** [comment]
Note to self: also happens for `delta`

**Comment by Naesstrom** [comment]
Still the same problem
![image](https://user-images.githubusercontent.com/6575206/152756484-ad9b0d16-2200-47e1-b90b-9017cf72fdd6.png)

**Comment by simphide** [comment]
Problem still exists
