### ISSUE TITLE
Wrong time format in max/min in Android Application

### ISSUE THREAD

**Issue by dcupaiolo** [kalkih/mini-graph-card#441]
In the android application, when you go to see the highs and lows, the time appears in am / pm format but instead of saying 12 PM it says 0 PM, the same graph on a Windows computer appears correctly. I attach images of the same graphic, one in android and one in Windows
![InkedScreenshot_20200906-143928_Home Assistant_LI](https://user-images.githubusercontent.com/65516654/92337376-84569100-f07f-11ea-9ac2-308b6591e85a.jpg)
![image](https://user-images.githubusercontent.com/65516654/92337402-d7c8df00-f07f-11ea-89f7-66abd33ea0e6.png)

**Comment by kalkih** [comment]
Hello,
The card utilize [toLocaleString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString) to render the time strings, so it's up to the browser to format the time correctly.
The locale used is based on the language set in your Home Assistant setup.

**Comment by dcupaiolo** [comment]
In what format does 0 PM exist? It's 12 AM or 12 PM, but 0 PM I've never seen...
0 is in 24 hour format, which does not have am or pm

**Comment by kalkih** [comment]
No idea...

**Comment by smiba** [comment]
Same happens on Chrome Desktop, Chrome Mobile and the Home Assistant app on Android.

![image](https://user-images.githubusercontent.com/3308142/142199602-15a94fe9-7af1-42c5-a646-09e42b476aa0.png)

Should probably be reopened, unless this really is a chrome bug. But a bug this size would probably have been fixed by now?

**Comment by MarphXL** [comment]
same here, correct settings for locale in HA, fresh installation (1x container, 1x supervised). problem still exists and is a little bit ugly with that am and pm and wrong separators
